### ISSUE TITLE
Make benchmarks hardware agnostic

### ISSUE THREAD

**Issue by sopel39** [prestodb/benchto#37]
Currently benchmarks contains attributes which are specific to the hardware and cluster:
- data size (10GB, 100GB, 1TB)
- number of runs, number of prewarms
- file format 

This makes reusing benchmarks on different clusters problematic since those elements need to be fine tuned to a given execution environment.

Major requirements of benchmarks are:
- results should have low variability
- execution time of benchmark should be reasonable (e.g: between 30s and 1min) in order to reduce static query overhead (e.g: client-server latency)

Having those requirements we propose to refactor benchto-driver and benchmarks in the following way:
- add `runs_scale_factor` driver parameter. Increasing this parameter would reduce variability of benchmark runtimes (this addresses your issue @idemura )
- use `catalog` (e.g: `tpch`) and `data_size` parameters in benchmarks instead of `schema`. `data_size` would be categorical variable (e.g: `tiny, small, medium, large, huge`). The purpose of the variable is to describe how "difficult" benchmark is to execute without specifying exact data size. This allows to use different mappings in various benchmark environments (e.g: `tpch_medium=tpch_10gb_text`). One definition of benchmark can be used to test different file formats. Additionally, the most appropriate data size should be used for environment so that benchmark runtime is reasonable.

FYI: @findepi @idemura

**Comment by idemura** [comment]
Thank you for quick response. Let's move all discussion here, in one place.

I can't agree that inheritance itself is bad as and idea. It works good in environments like Google borg, Google config language to name few and this is very convenient. What is problem there actually is that **every** parameter can be overriden. Before I explain approach to fix this, let's see what we try to solve here:
  - Add ability to override parameters,
  - Keep this under control (restrict) what can be overriden

Approach you suggest looks not generic enough. Every time something rises a new tiny-little-thingy that needs to be tuned we have to introduce more and more code in driver to support and so code of benchmark is coupled with Java code. I'd like to have this possibility in configs themselves.

I propose to fix inheritance. I totally agree that uncontrolled overriding can be a problem (and I observed such abuse at Google!). Let's only apply inheritance to designated section, say `params` or `overrides`. Other sections remain untouched by overrides (you can only replace them, as it was in a new file, or only add - we can figure out what behavior we want).

Example:
```
overrides:
  cluster: prn1
  catalog: movies

library:
  name: ${movies}
  url: master.${cluster}.facebook.com
  capacity: 100GB
```

If I need to tune this, I do in another file:
```
base: ../template/base.yaml

overrides:
  cluster: prn2
```

I see this to be:
  - Generic enough to not require custom Java code plumbing for new params
  - Overrides allow us to have generic templates decoupled with environment defines
  - Overrides are under control and you always know what you give to users to play with.

Thoughts?

**Comment by sopel39** [comment]
I think we are converging. I think we can mix approaches and decide on some convention (including inheritance).

Let's have example benchmark definition (`presto/tpch.yaml`):
```
datasource: presto
query-names: presto/tpch/${query}.sql
runs: 6
prewarm-runs: 2
before-execution: sleep-4s, presto/session_set_reorder_joins.sql, presto/session_set_join_distribution_type.sql
frequency: 7
database: hive

# default schema and data size mappings
tpch_tiny: 1gb
tpch_medium: 10gb

variables:
  1:
    query: q2, q8, q9
    schema: ${tpch_medium}
    reorder_joins: true
    join_distribution_type: automatic
```

Then we could have a "profile" yaml, for instance:
```
runs: 6
prewarm-runs: 2
tpch_tiny: 10gb

# NEW: it should be possible to override properties of individual benchmarks
presto.tpch.runs: 8
presto.tpch.tpch_tiny: 100gb
```
We could also have conventional (not enforced) overrides as you mentioned, e.g: benchmark:
```
...
overrides:
  tpch_tiny: 1gb

variables:
  1:
    query: q2, q8, q9
    schema: ${overrides.tpch_medium}
```
profile yaml:
```
overrides.tpch_tiny: 10gb
presto.tpch.overrides.tpch_tiny: 10gb
```

However, I think that inheritance should be explicit parameter to benchto driver instead of `base` path value, e.g:
```
--configuration overrides1.yml overrides2.yml
```
This way we could provide multiple override files (e.g: different overrides for tpch and tpchds) and bechto won't be additionally responsible for file resolution.

What do you think?

**Comment by idemura** [comment]
I'm not following everything, but seems to be quite complex because allows lots of ways to do same. In particular, I can't reason about profile yaml. Let's take example from above:
```
runs: 6
prewarm-runs: 2
tpch_tiny: 10gb

# NEW: it should be possible to override properties of individual benchmarks
presto.tpch.runs: 8
presto.tpch.tpch_tiny: 100gb

# Is this the same as:
presto:
  tpch:
    runs: 8
    tpch_tiny: 100gb
```
Q1: Is this file named like `teradata.profile.yaml`?
Q2: Is first section contains defaults, and second for particular benchmark and those from particular benchmark inherit from default one? If so, `presto.tpch.runs` should follow file name `presto/tpch.yaml`?
Q3: Do you restrict somehow what can be overriden?

As I understand, this is about moving all inheritance into one profile file, but inheritance is strictly from default profile?

Let me understand this. I think though we can have two separate for now and figure out what we want from inheritance, what exactly is duplicated and then return back to this.
